# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SpringBoot CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD


    - name: Build and Pushing Department-service
      run: mvn package dockerfile:push --file github_action/user-service/pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and Pushing User-service
      run: mvn package dockerfile:push --file github_action/department-service/pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and Pushing cloud-config-service
      run: mvn package dockerfile:push --file github_action/cloud-config-service/pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build and Pushing cloud-gateway
      run: mvn package dockerfile:push --file github_action/cloud-gateway/pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and Pushing hystrix-dashboard
      run: mvn package dockerfile:push --file github_action/hystrix-dashboard/pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and Pushing service-registry
      run: mvn package dockerfile:push --file github_action/service-registry/pom.xml
      env:
        MAVEN_USERNAME: ${{secrets.DOCKER_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master    
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
        CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
        ZONE_NAME: ${{ env.GKE_ZONE }}
      with:
        args: apply -f github_action/k8s/
